01-10-2025 13:20:09 ERROR [o.h.r.errors] (vert.x-eventloop-thread-4) HR000057: Failed to execute statement [select * from INFORMATION_SCHEMA.SEQUENCES]: could not execute query : java.util.concurrent.CompletionException: org.hibernate.exception.SQLGrammarException: error executing SQL statement [{number=18456, state=1, severity=14, message='Login failed for user 'sa'.', serverName='DESKTOP-VQ1ED8F\SQLEXPRESS', lineNumber=1}] [select * from INFORMATION_SCHEMA.SEQUENCES]
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:325)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:361)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:366)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:982)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:957)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:556)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2246)
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:602)
	at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:94)
	at io.vertx.core.Promise.fail(Promise.java:89)
	at io.vertx.core.Promise.handle(Promise.java:53)
	at io.vertx.core.Promise.handle(Promise.java:29)
	at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98)
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: org.hibernate.exception.SQLGrammarException: error executing SQL statement [{number=18456, state=1, severity=14, message='Login failed for user 'sa'.', serverName='DESKTOP-VQ1ED8F\SQLEXPRESS', lineNumber=1}] [select * from INFORMATION_SCHEMA.SEQUENCES]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:34)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:115)
	at org.hibernate.reactive.pool.impl.SqlClientPool.convertException(SqlClientPool.java:149)
	at org.hibernate.reactive.pool.impl.SqlClientPool.lambda$preparedQueryOutsideTransaction$1(SqlClientPool.java:136)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:980)
	... 27 more
Caused by: java.sql.SQLException: {number=18456, state=1, severity=14, message='Login failed for user 'sa'.', serverName='DESKTOP-VQ1ED8F\SQLEXPRESS', lineNumber=1}
	... 30 more

01-10-2025 13:20:09 ERROR [i.q.h.o.r.s.SchemaManagementIntegrator] (Hibernate post-boot validation thread for <default>) Failed to run post-boot validation: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.lambda$extractMetadata$0(SequenceInformationExtractorLegacyImpl.java:43)
	at org.hibernate.reactive.provider.service.ReactiveImprovedExtractionContextImpl.getQueryResults(ReactiveImprovedExtractionContextImpl.java:73)
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:36)
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:64)
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:58)
	at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:178)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:67)
	at io.quarkus.hibernate.orm.runtime.schema.SchemaManagementIntegrator.runPostBootValidation(SchemaManagementIntegrator.java:140)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$12.run(HibernateOrmRecorder.java:261)
	at java.base/java.lang.Thread.run(Thread.java:1447)

